spring:
  application:
    name: sca-product
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # Spring Insight配置
  insight:
    enabled: true
    service-name: sca-product
    datasource:
      url: jdbc:mysql://localhost:3306/spring_insight?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456

server:
  port: 8082