spring:
  application:
    name: sca-gateway
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: 93d3606d-ee6b-4cf9-9580-ed9844ba4bca
    gateway:
      routes:
        - id: order-service
          uri: lb://sca-order
          predicates:
            - Path=/order/**
        - id: product-service
          uri: lb://sca-product
          predicates:
            - Path=/product/**
        - id: user-service
          uri: lb://sca-user
          predicates:
            - Path=/user/**
  # Spring Insight配置
  insight:
    enabled: true
    service-name: sca-gateway
    datasource:
      url: jdbc:mysql://localhost:3306/spring-insight?useSSL=false&serverTimezone=UTC
      username: root
      password: 111111
    server:
      port: 8088

server:
  port: 8080