spring:
  application:
    name: sca-loyalty
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  # Spring Insight配置
  insight:
    enabled: true
    service-name: sca-loyalty
    datasource:
      url: jdbc:mysql://localhost:3306/spring-insight?useSSL=false&serverTimezone=UTC
      username: root
      password: 123456

server:
  port: 8084